spring:
  application:
    name: PortfolioManager
  jpa:
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      client:
         registration:
           github:
              clientId: 66591dd6252b020a4f8e
              clientSecret: f65273520b393b7cbd26646de5ddd4f00bd35450
              accessTokenUri: https://github.com/login/oauth/access_token
              userAuthorizationUri: https://github.com/login/oauth/authorize
         provider:
            github:
              user-info-uri: https://api.github.com/user 
              prefer-token-info: false
                
    user:
      password: user
    ignored: /,/favicon.ico,/index.html,/home.html,/portfolio_details.html,/stocks.html,/js/**,/css/**,/webjars/**
    sessions: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
    password: user
    dashboard:
      path: /eureka/dashboard 
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@localhost:9999/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

debug: false
server:
  port: 9999


logging:
 level:
    org.springframework.security: INFO
    com.netflix.discovery: INFO

---
spring:
  profiles: github_heroku
  security:
    oauth2:
      client:
         registration:
           github:      
              clientId: 2c67f85b2b3be28a6251
              clientSecret: e074e98c491f383d1ee3b580bca9f779073ac940
              accessTokenUri: https://github.com/login/oauth/access_token
              userAuthorizationUri: https://github.com/login/oauth/authorize
              clientAuthenticationScheme: form
         provider:
            github:
              user-info-uri: https://api.github.com/user 
              prefer-token-info: false              
      
eureka:
  password: user
  client:
    serviceUrl:
      defaultZone: https://user:${eureka.password}@stokker-portfolio-manager.herokuapp.com/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}            
            